set nocompatible

syntax enable

filetype plugin on

set path+=**
set wildmenu
set wildmode=longest:full,full

set number

" --- Generar tags desde Vim ---
set tags=./tags;/
command! MakeTags !ctags -R .

nnoremap <leader>t :MakeTags<CR>

" Edit vimrc
nnoremap <leader>ev :edit $MYVIMRC<CR>

" Source vimrc (reload)
nnoremap <leader>sv :source $MYVIMRC<CR>

" Busca la palabra bajo el cursor en todo el proyecto
nnoremap <leader>f :vimgrep /<C-r><C-w>/ ./**/*.py<CR>:copen<CR>
